name: Landing Build

on:
  push:
    branches:
      - main
      - dev
      - release-1.22.0
      - test

env:
  RELEASE_BRANCH: "release-1.22.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/release-1.23.0' || github.ref == 'refs/heads/test'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_STUDENT_APP }}
          known_hosts: unnecessary

      - name: Adding Known Hosts production MAIN
        if: github.ref == 'refs/heads/main'
        run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST_MAIN_PROD }}  >> ~/.ssh/known_hosts

      - name: 📂 Deploy with rsync production MAIN
        if: github.ref == 'refs/heads/main'
        run: rsync --archive --verbose --compress -c --delete-after --exclude=.git* --exclude=.git/ --exclude=README.es.md --exclude=README.en.md --exclude=README.pl.md --exclude=README.md --exclude=.gitignore --exclude=node_modules --exclude=ecosystem.config.js --exclude=.env --exclude=build --exclude=dist --exclude=.vscode ./dist/student-app/ ${{ secrets.SSH_USER_NAME_MAIN_PROD_FRONT }}@${{ secrets.SSH_HOST_MAIN_PROD }}:/var/www/ncodef/${{ secrets.SSH_HOST_MAIN_PROD }}

      - name: Adding Known Hosts release-1.23.0
        if: github.ref == 'refs/heads/release-1.23.0'
        run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST_RELEASE }}  >> ~/.ssh/known_hosts

      - name: 📂 Deploy with rsync release-1.23.0
        if: github.ref == 'refs/heads/release-1.23.0'
        run: rsync --archive --verbose --compress -c --delete-after --exclude=.git* --exclude=.git/ --exclude=README.es.md --exclude=README.en.md --exclude=README.pl.md --exclude=README.md --exclude=.gitignore --exclude=node_modules --exclude=ecosystem.config.js --exclude=.env --exclude=build --exclude=dist --exclude=.vscode ./dist/student-app/ ${{ secrets.SSH_USER_NAME_RELEASE_FRONT }}@${{ secrets.SSH_HOST_RELEASE }}:/var/www/ncoderelease/${{ secrets.SSH_HOST_RELEASE }}

      - name: Adding Known Hosts development DEV
        if: github.ref == 'refs/heads/dev'
        run: ssh-keyscan -p 22 -H n-code-dev.in.net  >> ~/.ssh/known_hosts

      - name: 📂 Deploy with rsync development DEV
        if: github.ref == 'refs/heads/dev'
        run: rsync --archive --verbose --compress -c --delete-after --exclude=.git* --exclude=.git/ --exclude=README.es.md --exclude=README.en.md --exclude=README.pl.md --exclude=README.md --exclude=.gitignore --exclude=node_modules --exclude=ecosystem.config.js --exclude=.env --exclude=build --exclude=dist --exclude=.vscode ./dist/student-app/ ${{ secrets.SSH_USER_NAME_DEV_FRONT }}@${{ secrets.SSH_HOST_DEV }}:/var/www/ncodedev/${{ secrets.SSH_HOST_DEV }}

      - name: Adding Known Hosts DEV => TEST
        if: github.ref == 'refs/heads/dev'
        run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST_TEST }}  >> ~/.ssh/known_hosts

      - name: 📂 Deploy with rsync DEV => TEST
        if: github.ref == 'refs/heads/dev'
        run: rsync --archive --verbose --compress -c --delete-after --exclude=.git* --exclude=.git/ --exclude=README.es.md --exclude=README.en.md --exclude=README.pl.md --exclude=README.md --exclude=.gitignore --exclude=node_modules --exclude=ecosystem.config.js --exclude=.env --exclude=build --exclude=dist --exclude=.vscode ./dist/student-app/ ${{ secrets.SSH_USER_NAME_TEST_FRONT }}@${{ secrets.SSH_HOST_TEST }}:/var/www/ncodetest/${{ secrets.SSH_HOST_TEST }}

      - name: Adding Known Hosts TEST
        if: github.ref == 'refs/heads/test'
        run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST_TEST }}  >> ~/.ssh/known_hosts

      - name: 📂 Deploy with rsync TEST
        if: github.ref == 'refs/heads/test'
        run: rsync --archive --verbose --compress -c --delete-after --exclude=.git* --exclude=.git/ --exclude=README.es.md --exclude=README.en.md --exclude=README.pl.md --exclude=.gitignore --exclude=node_modules --exclude=ecosystem.config.js --exclude=.env --exclude=build --exclude=dist --exclude=.vscode ./dist/student-app/ ${{ secrets.SSH_USER_NAME_TEST_FRONT }}@${{ secrets.SSH_HOST_TEST }}:/var/www/ncodetest/${{ secrets.SSH_HOST_TEST }}
# on:
#   push:
#     branches:
#       - main
#       - dev
#       - release-1.23.0
#       - test

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install SSH Key
#         if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/release-1.23.0' || github.ref == 'refs/heads/test'
#         uses: shimataro/ssh-key-action@v2
#         with:
#           key: ${{ secrets.SSH_KEY_STUDENT_APP }}
#           known_hosts: unnecessary

#       - name: Adding Known Hosts production MAIN
#         if: github.ref == 'refs/heads/main'
#         run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST_MAIN_PROD }}  >> ~/.ssh/known_hosts

#       - name: 📂 Deploy with rsync production MAIN
#         if: github.ref == 'refs/heads/main'
#         run: rsync --archive --verbose --compress -c --delete-after --exclude=.git* --exclude=.git/ --exclude=README.es.md --exclude=README.en.md --exclude=README.pl.md --exclude=README.md --exclude=.gitignore --exclude=node_modules --exclude=ecosystem.config.js --exclude=.env --exclude=build --exclude=dist --exclude=.vscode ./dist/student-app/ ${{ secrets.SSH_USER_NAME_MAIN_PROD_FRONT }}@${{ secrets.SSH_HOST_MAIN_PROD }}:/var/www/ncodef/${{ secrets.SSH_HOST_MAIN_PROD }}

#       - name: Adding Known Hosts release-1.23.0
#         if: github.ref == 'refs/heads/release-1.23.0'
#         run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST_RELEASE }}  >> ~/.ssh/known_hosts

#       - name: 📂 Deploy with rsync release-1.23.0
#         if: github.ref == 'refs/heads/release-1.23.0'
#         run: rsync --archive --verbose --compress -c --delete-after --exclude=.git* --exclude=.git/ --exclude=README.es.md --exclude=README.en.md --exclude=README.pl.md --exclude=README.md --exclude=.gitignore --exclude=node_modules --exclude=ecosystem.config.js --exclude=.env --exclude=build --exclude=dist --exclude=.vscode ./dist/student-app/ ${{ secrets.SSH_USER_NAME_RELEASE_FRONT }}@${{ secrets.SSH_HOST_RELEASE }}:/var/www/ncoderelease/${{ secrets.SSH_HOST_RELEASE }}

#       - name: Adding Known Hosts development DEV
#         if: github.ref == 'refs/heads/dev'
#         run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST_DEV }}  >> ~/.ssh/known_hosts

#       - name: 📂 Deploy with rsync development DEV
#         if: github.ref == 'refs/heads/dev'
#         run: rsync --archive --verbose --compress -c --delete-after --exclude=.git* --exclude=.git/ --exclude=README.es.md --exclude=README.en.md --exclude=README.pl.md --exclude=README.md --exclude=.gitignore --exclude=node_modules --exclude=ecosystem.config.js --exclude=.env --exclude=build --exclude=dist --exclude=.vscode ./dist/student-app/ ${{ secrets.SSH_USER_NAME_DEV_FRONT }}@${{ secrets.SSH_HOST_DEV }}:/var/www/ncodedev/${{ secrets.SSH_HOST_DEV }}

#       - name: Adding Known Hosts DEV => TEST
#         if: github.ref == 'refs/heads/dev'
#         run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST_TEST }}  >> ~/.ssh/known_hosts

#       - name: 📂 Deploy with rsync DEV => TEST
#         if: github.ref == 'refs/heads/dev'
#         run: rsync --archive --verbose --compress -c --delete-after --exclude=.git* --exclude=.git/ --exclude=README.es.md --exclude=README.en.md --exclude=README.pl.md --exclude=README.md --exclude=.gitignore --exclude=node_modules --exclude=ecosystem.config.js --exclude=.env --exclude=build --exclude=dist --exclude=.vscode ./dist/student-app/ ${{ secrets.SSH_USER_NAME_TEST_FRONT }}@${{ secrets.SSH_HOST_TEST }}:/var/www/ncodetest/${{ secrets.SSH_HOST_TEST }}

#       - name: Adding Known Hosts TEST
#         if: github.ref == 'refs/heads/test'
#         run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST_TEST }}  >> ~/.ssh/known_hosts

#       - name: 📂 Deploy with rsync TEST
#         if: github.ref == 'refs/heads/test'
#         run: rsync --archive --verbose --compress -c --delete-after --exclude=.git* --exclude=.git/ --exclude=README.es.md --exclude=README.en.md --exclude=README.pl.md --exclude=README.md --exclude=.gitignore --exclude=node_modules --exclude=ecosystem.config.js --exclude=.env --exclude=build --exclude=dist --exclude=.vscode ./dist/student-app/ ${{ secrets.SSH_USER_NAME_TEST_FRONT }}@${{ secrets.SSH_HOST_TEST }}:/var/www/ncodetest/${{ secrets.SSH_HOST_TEST }}
